config/routes.rb
# == Route Map
#
#                           Prefix Verb   URI Pattern                                                                              Controller#Action
#                letter_opener_web        /letter_opener                                                                           LetterOpenerWeb::Engine
#                      sidekiq_web        /sidekiq                                                                                 Sidekiq::Web
#                             root GET    /                                                                                        posts#index
#                            login GET    /login(.:format)                                                                         user_sessions#new
#                                  POST   /login(.:format)                                                                         user_sessions#create
#                           logout DELETE /logout(.:format)                                                                        user_sessions#destroy
#                            users GET    /users(.:format)                                                                         users#index
#                                  POST   /users(.:format)                                                                         users#create
#                         new_user GET    /users/new(.:format)                                                                     users#new
#                             user GET    /users/:id(.:format)                                                                     users#show
#                    post_comments GET    /posts/:post_id/comments(.:format)                                                       comments#index
#                                  POST   /posts/:post_id/comments(.:format)                                                       comments#create
#                 new_post_comment GET    /posts/:post_id/comments/new(.:format)                                                   comments#new
#                     edit_comment GET    /comments/:id/edit(.:format)                                                             comments#edit
#                          comment GET    /comments/:id(.:format)                                                                  comments#show
#                                  PATCH  /comments/:id(.:format)                                                                  comments#update
#                                  PUT    /comments/:id(.:format)                                                                  comments#update
#                                  DELETE /comments/:id(.:format)                                                                  comments#destroy
#                     search_posts GET    /posts/search(.:format)                                                                  posts#search
#                            posts GET    /posts(.:format)                                                                         posts#index
#                                  POST   /posts(.:format)                                                                         posts#create
#                         new_post GET    /posts/new(.:format)                                                                     posts#new
#                        edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                             post GET    /posts/:id(.:format)                                                                     posts#show
#                                  PATCH  /posts/:id(.:format)                                                                     posts#update
#                                  PUT    /posts/:id(.:format)                                                                     posts#update
#                                  DELETE /posts/:id(.:format)                                                                     posts#destroy
#                            likes POST   /likes(.:format)                                                                         likes#create
#                             like DELETE /likes/:id(.:format)                                                                     likes#destroy
#                    relationships POST   /relationships(.:format)                                                                 relationships#create
#                     relationship DELETE /relationships/:id(.:format)                                                             relationships#destroy
#                    read_activity PATCH  /activities/:id/read(.:format)                                                           activities#read
#              edit_mypage_account GET    /mypage/account/edit(.:format)                                                           mypage/accounts#edit
#                   mypage_account PATCH  /mypage/account(.:format)                                                                mypage/accounts#update
#                                  PUT    /mypage/account(.:format)                                                                mypage/accounts#update
#                mypage_activities GET    /mypage/activities(.:format)                                                             mypage/activities#index
# edit_mypage_notification_setting GET    /mypage/notification_setting/edit(.:format)                                              mypage/notification_settings#edit
#      mypage_notification_setting PATCH  /mypage/notification_setting(.:format)                                                   mypage/notification_settings#update
#                                  PUT    /mypage/notification_setting(.:format)                                                   mypage/notification_settings#update
#               rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#        rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#               rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#        update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#             rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment

require 'sidekiq/web'

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
    mount Sidekiq::Web, at: '/sidekiq'
  end
  root to: 'posts#index'

  get '/login', to: 'user_sessions#new'
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'

  resources :users, only: %i[index new create show]
  resources :posts, shallow: true do
    resources :comments
    collection do
      get :search
    end
  end
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :activities, only: %i[] do
    patch :read, on: :member
  end

  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end
end

app/views/shared/_commented_to_own_post.html.slim
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do 
  = image_tag activity.subject.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  object
    = link_to activity.subject.user.username, user_path(activity.subject.user)
  | があなたの
  object
    = link_to '投稿', post_path(activity.subject.post)
  | に
  object
    = link_to 'コメント', post_path(activity.subject.post, anchor: "comment-#{activity.subject.id}")
  | しました
  .ml-auto 
    = l activity.created_at, format: :short

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  #error_messages.alert.alert-danger
    ul.mb-0
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_flash_messages.html.slim
- flash.each do |message_type, message|
  div class=("alert alert-#{message_type}") = message

app/views/shared/_followed_me.html.slim
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read}", method: :patch do
  = image_tag activity.subject.follower.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  object
    = link_to activity.subject.follower.username, user_path(activity.subject.follower)
  | があなたをフォローしました
  .ml-auto 
    = l activity.created_at, format: :short

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstaClone', root_path, class: 'navbar-brand'
  / 表示サイズによりメニューを非表示にし、メニューバーを実行
  button.navbar-toggler aria-controls='navbarTogglerDemo02' aria-expanded='false' aria-label=('Toggle navigation') data-target='#navbarTogglerDemo02' data-toggle='collapse' type='button'
    span.navbar-toggler-icon
  / メニューの表示内容（折り畳まれる）
  #navbarTogglerDemo02.collapse.navbar-collapse
    / 検索窓
    = render 'posts/search_form', search_form: @search_form
    / リンク   
    ul.navbar-nav.mt-2.mt-lg-0 
      li.nav-item
        = link_to new_post_path, class: 'nav-link' do
          = icon 'far', 'image', class:'fa-lg'
      li.nav-item
        .dropdown 
          a#dropdownMenuButton.nav-link.position-relative href="#" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true"
            = icon 'far', 'heart', class: 'fa-lg'
            = render 'shared/unread_badge'
          #header-activities.dropdown-menu.dropdown-menu-right.m-0.p-0 aria-labelledby="dropdownMenuButton"
            = render'shared/header_activities'

      li.nav-item
        = link_to user_path(current_user), class: 'nav-link' do
          = icon 'far', 'user', class:'fa-lg'
      li.nav-item 
          = link_to 'ログアウト', logout_path, class: 'nav-link', method: :delete

app/views/shared/_header_activities.html.slim
- if current_user.activities.present?
  - current_user.activities.recent(10).each do |activity|
    = render "shared/#{activity.action_type}", activity: activity
  - if current_user.activities.count > 10
    = link_to 'すべてみる', mypage_activities_path, class: 'dropdown-item justify-content-center'
- else 
  .dropdown-item 
    | お知らせはありません
    

app/views/shared/_header_before_login.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'InstaClone', root_path, class: 'navbar-brand'
  / 表示サイズによりメニューを非表示にし、メニューバーを実行
  button.navbar-toggler aria-controls='navbarTogglerDemo02' aria-expanded='false' aria-label=('Toggle navigation') data-bs-target='#navbarTogglerDemo02' data-toggle='collapse' type='button'
    span.navbar-toggler-icon
  / メニューの表示内容（折り畳まれる）
  #navbarTogglerDemo02.collapse.navbar-collapse
    / / 検索窓
    = render 'posts/search_form', search_form: @search_form
    / リンク
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item 
        = link_to 'ポスト一覧', posts_path, class:'nav-link'
      li.nav-item 
        = link_to 'ログイン', login_path, class: 'nav-link'

app/views/shared/_liked_to_own_post.html.slim
= link_to read_activity_path(activity), class: "dropdown-item border-bottom #{'read' if activity.read?}", method: :patch do 
  = image_tag activity.subject.user.avatar.url, class: 'rounded-circle mr-1', size: '30x30'
  object
    = link_to activity.subject.user.username, user_path(activity.subject.user)
  | があなたの
  object
    = link_to '投稿', post_path(activity.subject.post) 
  | にいいねしました
  .ml-auto 
    = l activity.created_at, format: :short

app/views/shared/_modal.html.slim
#modal-container

app/views/shared/_unread_badge.html.slim
- if current_user.activities.unread.count > 0
  span.badge.badge-warning.navbar-badge.position-absolute style='top: 0; right:0;'
    = current_user.activities.unread.count