config/routes.rb
# == Route Map
#
#                           Prefix Verb   URI Pattern                                                                              Controller#Action
#                letter_opener_web        /letter_opener                                                                           LetterOpenerWeb::Engine
#                      sidekiq_web        /sidekiq                                                                                 Sidekiq::Web
#                             root GET    /                                                                                        posts#index
#                            login GET    /login(.:format)                                                                         user_sessions#new
#                                  POST   /login(.:format)                                                                         user_sessions#create
#                           logout DELETE /logout(.:format)                                                                        user_sessions#destroy
#                            users GET    /users(.:format)                                                                         users#index
#                                  POST   /users(.:format)                                                                         users#create
#                         new_user GET    /users/new(.:format)                                                                     users#new
#                             user GET    /users/:id(.:format)                                                                     users#show
#                    post_comments GET    /posts/:post_id/comments(.:format)                                                       comments#index
#                                  POST   /posts/:post_id/comments(.:format)                                                       comments#create
#                 new_post_comment GET    /posts/:post_id/comments/new(.:format)                                                   comments#new
#                     edit_comment GET    /comments/:id/edit(.:format)                                                             comments#edit
#                          comment GET    /comments/:id(.:format)                                                                  comments#show
#                                  PATCH  /comments/:id(.:format)                                                                  comments#update
#                                  PUT    /comments/:id(.:format)                                                                  comments#update
#                                  DELETE /comments/:id(.:format)                                                                  comments#destroy
#                     search_posts GET    /posts/search(.:format)                                                                  posts#search
#                            posts GET    /posts(.:format)                                                                         posts#index
#                                  POST   /posts(.:format)                                                                         posts#create
#                         new_post GET    /posts/new(.:format)                                                                     posts#new
#                        edit_post GET    /posts/:id/edit(.:format)                                                                posts#edit
#                             post GET    /posts/:id(.:format)                                                                     posts#show
#                                  PATCH  /posts/:id(.:format)                                                                     posts#update
#                                  PUT    /posts/:id(.:format)                                                                     posts#update
#                                  DELETE /posts/:id(.:format)                                                                     posts#destroy
#                            likes POST   /likes(.:format)                                                                         likes#create
#                             like DELETE /likes/:id(.:format)                                                                     likes#destroy
#                    relationships POST   /relationships(.:format)                                                                 relationships#create
#                     relationship DELETE /relationships/:id(.:format)                                                             relationships#destroy
#                    read_activity PATCH  /activities/:id/read(.:format)                                                           activities#read
#              edit_mypage_account GET    /mypage/account/edit(.:format)                                                           mypage/accounts#edit
#                   mypage_account PATCH  /mypage/account(.:format)                                                                mypage/accounts#update
#                                  PUT    /mypage/account(.:format)                                                                mypage/accounts#update
#                mypage_activities GET    /mypage/activities(.:format)                                                             mypage/activities#index
# edit_mypage_notification_setting GET    /mypage/notification_setting/edit(.:format)                                              mypage/notification_settings#edit
#      mypage_notification_setting PATCH  /mypage/notification_setting(.:format)                                                   mypage/notification_settings#update
#                                  PUT    /mypage/notification_setting(.:format)                                                   mypage/notification_settings#update
#               rails_service_blob GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                               active_storage/blobs#show
#        rails_blob_representation GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations#show
#               rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                              active_storage/disk#show
#        update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                      active_storage/disk#update
#             rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                           active_storage/direct_uploads#create
#
# Routes for LetterOpenerWeb::Engine:
# clear_letters DELETE /clear(.:format)                 letter_opener_web/letters#clear
# delete_letter DELETE /:id(.:format)                   letter_opener_web/letters#destroy
#       letters GET    /                                letter_opener_web/letters#index
#        letter GET    /:id(/:style)(.:format)          letter_opener_web/letters#show
#               GET    /:id/attachments/:file(.:format) letter_opener_web/letters#attachment

require 'sidekiq/web'

Rails.application.routes.draw do
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
    mount Sidekiq::Web, at: '/sidekiq'
  end
  root to: 'posts#index'

  get '/login', to: 'user_sessions#new'
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'

  resources :users, only: %i[index new create show]
  resources :posts, shallow: true do
    resources :comments
    collection do
      get :search
    end
  end
  resources :likes, only: %i[create destroy]
  resources :relationships, only: %i[create destroy]
  resources :activities, only: %i[] do
    patch :read, on: :member
  end

  namespace :mypage do
    resource :account, only: %i[edit update]
    resources :activities, only: %i[index]
    resource :notification_setting, only: %i[edit update]
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  body       :text(65535)      not null
#  images     :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint
#
# Indexes
#
#  index_posts_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Post < ApplicationRecord
  belongs_to :user

  mount_uploaders :images, ImagesUploader
  serialize :images, JSON

  validates :images, presence: true
  validates :body, presence: true, length: { maximum: 1000 }

  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_users, through: :likes, source: :user

  scope :body_contain, ->(word) { where('posts.body LIKE ?', "%#{word}%") }
  scope :comment_body_contain, ->(word) { joins(:comments).where('comments.body LIKE ?', "%#{word}%") }
  scope :username_contain, ->(word) { joins(:user).where('username LIKE ?', "%#{word}%") }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: %i[new create edit update destroy]
  def index
    @posts = if current_user
               current_user.feed.includes(:user).page(params[:page]).order(created_at: :desc)
             else
               Post.all.includes(:user).page(params[:page]).order(created_at: :desc)
             end
    @users = User.recent(5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to posts_path, success: '投稿しました'
    else
      flash.now[:danger] = '投稿に失敗しました。'
      render :new
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])
    if @post.update(post_params)
      redirect_to posts_path, success: '投稿を更新しました。'
    else
      flash.now[:danger] = '投稿の更新に失敗しました。'
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.includes(:user).order(created_at: :desc)
    @comment = Comment.new
  end

  def destroy
    @post = current_user.posts.find(params[:id])
    @post.destroy!
    redirect_to posts_path, success: '投稿を削除しました。'
  end

  def search
    @posts = @search_form.search.includes(:user).page(params[:page])
  end

  private

  def post_params
    params.require(:post).permit(:body, images: [])
  end
end

app/views/posts/_form.html.slim
= form_with model: post, local: true, id: 'posts_form' do |f|
  = render 'shared/error_messages', object: post
  .form-group
    = f.label :images
    = f.file_field :images, multiple: true, class: 'form-control'
    - post.images.each do |image|
      = image_tag image.url, size: '100x100', class: 'image-thumbnail'
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
  = f.submit class:'btn btn-primary btn-raised'

app/views/posts/_like.html.slim
= link_to likes_path(post_id: post.id), method: :post, class: 'like-button', remote: true do 
  = icon 'far', 'heart', class: 'fa-lg'

app/views/posts/_like_area.html.slim
div id="like_area-#{post.id}"
  - if current_user.like?(post)
    = render 'unlike', post: post
  - else
    = render 'like', post: post

app/views/posts/_post.html.slim
.card.mb-5.post id="post-#{post.id}"
  .card-header 
    .d-flex.align-items-center
      = link_to user_path(post.user) do
        = image_tag post.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
        = post.user.username 
      - if current_user&.own?(post)
        .ml-auto 
          = link_to post_path(post), class: 'mr-3, delete-button', method: :delete, data: { confirm:'本当に削除しますか？' } do
            = icon 'far', 'trash-alt', class: 'fa-lg'
          = link_to edit_post_path(post), class:'edit-button' do 
            = icon 'far', 'edit', class:'fa-lg'
      - if current_user && !current_user.own?(post)
        .ml-auto 
          = render 'like_area', post: post   
  = link_to post_path(post) do
    .swiper
      .swiper-wrapper 
        - post.images.each do |image|
          .swiper-slide 
            = image_tag image.url, class: 'card-img-top'
      .swiper-pagination
  .card-body 
    .card-text
      = post.body

app/views/posts/_search_form.html.slim
  = form_with model: search_form, url: search_posts_path, scope: :q, class: 'form-inline my-2 my-lg-0 mr-auto', method: :get, local: true do |f|
    = f.search_field :body, class: 'form-control mr-sm-2', placeholder: '本文'
    = f.search_field :comment_body, class: 'form-control mr-sm-2', placeholder: 'コメント'
    = f.search_field :username, class: 'form-control mr-sm-2', placeholder: 'ユーザー名'
    = f.submit 'Search', class: 'btn btn-outline-success my-2 my-sm-0'

app/views/posts/_thumbnail_post.html.slim
.col-md-4.mb-3 
  = link_to post_path(thumbnail_post), class: 'thumbs' do 
    = image_tag thumbnail_post.images.first.url

app/views/posts/_unlike.html.slim
= link_to like_path(current_user.likes.find_by(post_id: post.id)), method: :delete, class: 'unlike-button', remote: true do 
  = icon 'fas', 'heart', class: 'fa-lg'

app/views/posts/edit.html.slim
.container 
  .row 
    .col-md-6.col-12.offset-3
      .card 
        .card-body 
          = render 'form', post: @post

app/views/posts/index.html.slim
.container 
  .row 
    .col-md-8.col-12
      - if @posts.present?
        = render @posts
      - else 
        .text-center.font-weight-bold
          | 投稿がありません
      = paginate @posts
    .col-md-4.col-12
      - if logged_in?
        .profile-box.mb-3 
          = image_tag current_user.avatar.url, size: '50x50', class: 'rounded-circle mr-1' 
          = link_to current_user.username, edit_mypage_account_path 
      .users-box
        .card 
          .card-header
            | ユーザー 
          .card-body
            = render @users
          .card-footer 
            = link_to 'すべて見る', users_path

app/views/posts/new.html.slim
.container 
  .row 
    .col-md-6.col-12.offset-md-3 
      .card 
        .card-body 
          = render 'form', post: @post

app/views/posts/search.html.slim
.container 
  .row 
    .col-md-8.col-12.offset-md-2 
      h2.text-center 
        | 検索結果: #{@posts.total_count}件
      = render @posts
      = paginate @posts

app/views/posts/show.html.slim
- set_meta_tags title: '投稿詳細ページ', description: @post.body,
  og: { image: "#{request.base_url}#{@post.images.first.url}"}
.post-detail.card
  .image-box 
    .swiper
      .swiper-wrapper
        - @post.images.each do |image|
          .swiper-slide
            = image_tag image.url
      .swiper-pagination
  .image-info-box
    .profile-box.p-3
      .d-flex.align-items-center
        = image_tag @post.user.avatar.url, size: '40x40', class: 'rounded-circle mr-1'
        = @post.user.username
        - if current_user&.own?(@post)
          .ml-auto 
            = link_to post_path(@post), class: 'mr-3', method: :delete, data: { confirm: '本当に削除しますか？' } do 
              = icon 'far', 'trash-alt', class: 'fa-lg'
            = link_to edit_post_path(@post), class: 'mr-3' do 
              = icon 'far', 'edit', class: 'fa-lg'
        - if current_user && !current_user.own?(@post)
          .ml-auto 
            = render 'like_area', post: @post
    hr.m-0
    .post-body.p-3
      / 投稿の本文
      .row.no-gutters
        .col-2 
          = image_tag @post.user.avatar.url, size: '40x40', class: 'rounded-circle'
        .col-10
          = simple_format(@post.body)
      hr
      / コメント一覧
      = render 'comments/comments', comments: @comments 
    hr.m-0
    .post-comment.p-3
      = render 'comments/form', post: @post, comment: @comment